sonar.organization=skodua
sonar.projectKey=skodua_xashy-university-portal
sonar.sources=src/main/java, src/main/webapp
sonar.tests=src/test/java

# Required for Java analysis when using the standalone scanner with a Maven build
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml


# sonar.sourceEncoding=UTF-8
# sonar.java.binaries=target/classes
# sonar.host.url=${env.SONAR_HOST_URL}