name: Build, test and package mvn artifact with SAST
on:
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of SonarCloud analysis
      
      - name: Setup Java 
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin' 
          java-version: '11'
          cache: maven
      
      - name: Run tests and generate coverage reports
        run: mvn clean verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
      
      - name: SAST with SonarCloud 
        run: mvn sonar:sonar -Psonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: war-artifact
          path: target/*.war
      