name: Build and deploy xashy-student-portal
on: 
  push:
    branches:
      - main
jobs: 
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Clone the repo 
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
           distribution: temurin
           java-version: '11'
           cache: maven
      
      - name: Build with Maven 
        run: mvn clean package 
      
      - name: Deploy to GitHub Packages 
        run: mvn deploy --settings settings.xml
       
