name: Build, test and package mvn artifact with SAST
on:
  push: 
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4
      
      - name: Setup Java 
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: maven
      
      - name: package with maven
        run: mvn clean package
        
      - name: SAST with SonarCloud 
        run: mvn sonar:sonar -Psonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
