name:  Build and deploy xashy-student-portal

on: 
  push:
    branches:
      - main

jobs: 

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo 
        uses: actions/checkout@v4
      - name: setup maven and java
        uses: actions/setup-java@v4
        with:
          distribution: temurin 
          java-version: '11'
          cache: maven
      - name: build with maven 
        run: mvn clean package 


    
