name: test github actions 
on: 
  push: 
    branches: ["main"]
jobs: 
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: update ubuntu
        run: sudo apt update -y
      - name: download cli zip
        run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && sudo ./aws/install
      - name: confirms the awscli version
        run: aws --version
